name: portainer

services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/portainer:/data
