version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.19.4
    restart: always
    ports:
      - 10000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:rw
      - /data/portainer:/data