name: emqx

services:
  emqx:
    image: emqx/emqx:5.6.1
    restart: always
    user: root
    environment:
      EMQX_NAME: emqx
      EMQX_HOST: ${IP}
      EMQX_DASHBOARD__DEFAULT_PASSWORD: aA123456!
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 18083:18083
    volumes:
      - ./data/emqx:/opt/emqx/data
      - ./logs/emqx:/opt/emqx/log
  nginx:
    image: nginx:1.24
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/web:/usr/share/nginx/html
      - ./apps/nginx/conf.d:/etc/nginx/conf.d
      - ./apps/nginx/cert:/etc/nginx/cert
    depends_on:
      - emqx
  # emqx2:
  #   image: emqx/emqx:5.6.1
  #   restart: always
  #   user: root
  #   environment:
  #     EMQX_NAME: emqx
  #     EMQX_HOST: ${IP}
  #     EMQX_DASHBOARD__DEFAULT_PASSWORD: aA123456!
  #   ports:
  #     - 1884:1883
  #     - 18084:18083
  #   volumes:
  #     - ./data/emqx2:/opt/emqx/data
  #     - ./logs/emqx2:/opt/emqx/log
