name: drone

services:
  gitea:
    # https://docs.gitea.com/zh-cn/installation/install-with-docker-rootless
    image: gitea/gitea:${GITEA_VERSION}
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
    ports:
      - ${GITEA_PORT_HTTP}:3000
      - ${GITEA_PORT_SSH}:22
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/gitea:/data
  drone:
    image: drone/drone:${DRONE_VERSION}
    restart: always
    privileged: true
    environment:
      - DRONE_GITEA_SERVER=http://${IP}:${GITEA_PORT_HTTP}
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_SERVER_HOST=${IP}:${DRONE_SERVER_PORT}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_GIT_ALWAYS_AUTH=${DRONE_GIT_ALWAYS_AUTH}
      - DRONE_USER_CREATE=${DRONE_USER_CREATE}
    ports:
      - ${DRONE_SERVER_PORT}:80
    volumes:
      - ./data/drone:/data
    depends_on:
      - gitea
  drone-runner-docker:
    image: drone/drone-runner-docker:1.8.3
    restart: always
    environment:
      - DRONE_RPC_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_HOST=${IP}:${DRONE_SERVER_PORT}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=drone-runner-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone
