name: gitea

services:
  gitea:
    # https://docs.gitea.com/zh-cn/installation/install-with-docker-rootless
    image: gitea/gitea:${GITEA_VERSION}
    restart: always
    ports:
      - 3000:3000
      - 2222:22
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./data/gitea:/data
  gitea_runner:
    # https://docs.gitea.com/zh-cn/usage/actions/act-runner#%E4%BD%BF%E7%94%A8-docker-compose-%E8%BF%90%E8%A1%8C-runner
    # https://github.com/dufok/dokku-act-runner/blob/4992822de2026a702c24491b91f5fcffc7bcb22d/examples/docker-compose/README.md
    image: gitea/act_runner:${ACT_RUNNER_VERSION}
    restart: always
    privileged: true
    environment:
      # - DOCKER_HOST=unix:///var/run/user/1000/docker.sock
      - GITEA_INSTANCE_URL=${GITEA_INSTANCE_URL}
      - GITEA_RUNNER_REGISTRATION_TOKEN=${REGISTRATION_TOKEN}
    depends_on:
      - gitea
    volumes:
      - ./data/act_runner:/data
      - /var/run/docker.sock:/var/run/docker.sock
