name: odoo

services:
  odoo:
    image: odoo:17.0
    ports:
      - 8070:8069
      - 8073:8072
    volumes:
      - ./apps/odoo/config:/etc/odoo
      - ./apps/odoo/data:/var/lib/odoo
      - ./apps/odoo/addons:/mnt/extra-addons
    depends_on:
      - postgres
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5433:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
