services:
  wta:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
  #分布式文件系统
  minio: 
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=aA123456!
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/minio:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
  #分布式缓存
  redis:
    image: redis:7.4.0
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
  #关系数据库
  mysql:
    image: mysql:8.4.2
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=aA123456!
    ports:
      - 3306:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    command: --mysql_native_password=on
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 10s
  #分布式数据库
  # cockroachdb:
  #   image: cockroachdb/cockroach:v24.2.0
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #    - 26257:26257
  #    - 8080:8080
  #   command: start-single-node --insecure
  #   volumes:
  #    - ./data/cockroachdb:/cockroach/cockroach-data
  # oceanbase:
  #   image: oceanbasedev/oceanbase-ce:4.2.1-lts
  #   environment:
  #     - MODE=mini
  #   ports:
  #    - 2881:2881
  #   volumes:
  #    - ./data/oceanbase:/root/ob

