networks:
 net:
    name: wta_net
    external: true

services:
  wta:
    image: ${DOCKER_REGISTRY-}wta
    build:
      context: .
      dockerfile: src/Wta/Dockerfile
    ports:
      - 5000:80
    networks:
      - net
